version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout # Bước 1: Lấy code từ GitHub về máy ảo CircleCI
      - run:
          name: Build and Run Tests
          command: mvn test # Bước 2: Lệnh quan trọng nhất để chạy JUnit Test

workflows:
  sample:
    jobs:
      - build-and-test